-- In Supabase im SQL Editor vollständig ausführen.
-- WICHTIG: Ersetze unten MEIN-SICHERES-ADMIN-PASSWORT durch dein eigenes Passwort.

create extension if not exists pgcrypto;

create table if not exists public.bingo_entries (
  id bigint generated by default as identity primary key,
  client_id uuid not null,
  player text not null check (player in ('florian','justin','sergey','michael','michael pufe','viktor','simon')),
  target text not null check (target in ('florian','justin','sergey','michael','michael pufe','viktor','simon')),
  slot integer not null check (slot between 0 and 4),
  word text not null default '' check (char_length(word) <= 80),
  checked boolean not null default false,
  updated_at timestamptz not null default now(),
  unique (client_id, player, target, slot),
  check (player <> target)
);

alter table public.bingo_entries enable row level security;
revoke all on public.bingo_entries from anon, authenticated;
revoke all on sequence public.bingo_entries_id_seq from anon, authenticated;

-- Die Spielseite kann ausschließlich über diese eng begrenzte Funktion
-- genau einen ihrer lokalen Slots einfügen oder aktualisieren.
create or replace function public.upsert_bingo_entry(
  p_client_id uuid,
  p_player text,
  p_target text,
  p_slot integer,
  p_word text,
  p_checked boolean
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if p_player not in ('florian','justin','sergey','michael','michael pufe','viktor','simon')
     or p_target not in ('florian','justin','sergey','michael','michael pufe','viktor','simon')
     or p_player = p_target
     or p_slot not between 0 and 4
     or char_length(coalesce(p_word,'')) > 80 then
    raise exception 'invalid bingo entry';
  end if;

  insert into public.bingo_entries(client_id,player,target,slot,word,checked,updated_at)
  values (p_client_id,p_player,p_target,p_slot,coalesce(p_word,''),coalesce(p_checked,false),now())
  on conflict (client_id,player,target,slot)
  do update set
    word = excluded.word,
    checked = excluded.checked,
    updated_at = now();
end;
$$;

revoke all on function public.upsert_bingo_entry(uuid,text,text,integer,text,boolean) from public;
grant execute on function public.upsert_bingo_entry(uuid,text,text,integer,text,boolean) to anon;

-- Passwort-Hash getrennt und nicht öffentlich lesbar speichern.
create table if not exists public.bingo_admin_config (
  singleton boolean primary key default true check (singleton),
  password_hash text not null
);
alter table public.bingo_admin_config enable row level security;
revoke all on public.bingo_admin_config from anon, authenticated;

insert into public.bingo_admin_config(singleton,password_hash)
values (true, crypt('Michiabend', gen_salt('bf')))
on conflict (singleton) do update set password_hash=excluded.password_hash;

-- Nur diese Funktion darf die globale Auswertung lesen.
create or replace function public.get_bingo_summary(admin_password text)
returns table(target text, word text, mentions bigint)
language plpgsql
security definer
set search_path = public
as $$
begin
  if not exists (
    select 1 from public.bingo_admin_config
    where singleton = true
      and password_hash = crypt(admin_password, password_hash)
  ) then
    raise exception 'invalid admin password';
  end if;

  return query
  select
    lower(trim(e.target)) as target,
    min(trim(e.word)) as word,
    count(*)::bigint as mentions
  from public.bingo_entries e
  where trim(e.word) <> ''
  group by lower(trim(e.target)), lower(trim(e.word))
  order by lower(trim(e.target)), count(*) desc, lower(trim(e.word));
end;
$$;

revoke all on function public.get_bingo_summary(text) from public;
grant execute on function public.get_bingo_summary(text) to anon;
